---

- name: Ensure Woodpecker CI agent image is pulled
  community.docker.docker_image:
    name: "{{ devture_woodpecker_ci_agent_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ devture_woodpecker_ci_agent_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else devture_woodpecker_ci_agent_container_image_force_pull }}"

- name: Ensure Woodpecker CI agent paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ devture_woodpecker_ci_agent_uid }}"
    group: "{{ devture_woodpecker_ci_agent_gid }}"
  with_items:
    - "{{ devture_woodpecker_ci_agent_base_path }}"

- name: Ensure Woodpecker CI agent support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ devture_woodpecker_ci_agent_base_path }}/{{ item }}"
    owner: "{{ devture_woodpecker_ci_agent_uid }}"
    group: "{{ devture_woodpecker_ci_agent_gid }}"
    mode: 0640
  with_items:
    - env

- name: Ensure Woodpecker CI agent systemd service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/woodpecker-ci-agent.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ devture_woodpecker_ci_agent_identifier }}.service"
    mode: 0640
